
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wetgymqgqraieknqagid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndldGd5bXFncXJhaWVrbnFhZ2lkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5NjY0NzUsImV4cCI6MjA1NTU0MjQ3NX0.pW8d14sVFQNhqtQXoA08-wPzLGgIgD1CqP7JFfftmiw";

// Create and export the Supabase client with proper configuration
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true
    }
  }
);
