
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhawzqabdsfcnudhhpka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InloYXd6cWFiZHNmY251ZGhocGthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5Njc4MTksImV4cCI6MjA1NTU0MzgxOX0.NBNQNu3fr1n9dmaV6J70WuGPTvlYMg10qtkCiHCsFiY";

// Create and export the Supabase client with proper configuration
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true
    }
  }
);
